### ISSUE TITLE
have runtimeError after epoch 199

### ISSUE THREAD

**Issue by HagridThick** [deepakn97/relationPrediction#25]
Iteration-> 674  , Iteration_time-> 0.1287 , Iteration_loss 0.0011
Iteration-> 675  , Iteration_time-> 0.1287 , Iteration_loss 0.0010
Iteration-> 676  , Iteration_time-> 0.1297 , Iteration_loss 0.0009
Iteration-> 677  , Iteration_time-> 0.1297 , Iteration_loss 0.0009
Iteration-> 678  , Iteration_time-> 0.0578 , Iteration_loss 0.0013
Epoch 199 , average loss 0.0010276363643238785 , epoch_time 88.21463370323181
Saving Model
Done saving Model
Sampled indices
test set length  3134
0
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    evaluate_conv(args, Corpus_.unique_entities_train)
  File "main.py", line 363, in evaluate_conv
    Corpus_.get_validation_pred(args, model_conv, unique_entities)
  File "C:\Users\a\Documents\GitHub\relationPrediction\create_batch.py", line 423, in get_validation_pred
    new_x_batch_head[:num_triples_each_shot, :]).cuda())
  File "C:\Users\a\Documents\GitHub\relationPrediction\models.py", line 208, in batch_test
    out_conv = self.convKB(conv_input)
  File "D:\anaconda3\envs\python37-pytorch10.2\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\a\Documents\GitHub\relationPrediction\layers.py", line 35, in forward
    self.non_linearity(self.conv_layer(conv_input)))
  File "D:\anaconda3\envs\python37-pytorch10.2\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\python37-pytorch10.2\lib\site-packages\torch\nn\modules\conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "D:\anaconda3\envs\python37-pytorch10.2\lib\site-packages\torch\nn\modules\conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 3.81 GiB (GPU 0; 11.00 GiB total capacity; 3.87 GiB already allocated; 2.55 GiB free; 5.81 GiB reserved in total by PyTorch)

__________________
 i used this command  $ python3 main.py --get_2hop True
and it says CUDA out of memory  after epoch 199, what parameters should i change to finish this training?
thank you

**Comment by chauhanjatin10** [comment]
Hi @HagridThick .Thanks for showing interest in our work. I think you got memory issues while evaluating the model rather than during the final training epoch. During evaluation, we use one-vs-all strategy by replacing first the head entity then the tail entity with all possible nodes in the graph and then perform the ranking. This can potentially incur large memory than during training based on the batch size. I suggest you decrease the value of "num_triples_each_shot" parameter in line 419 and 460 of create_batch.py file. This splits the input into multiple smaller batches and then concatenate the final prediction scores to perform ranking as written in line 443. I hope this clarifies.
Thanks
